package All_Forms;


import DataHolder.Dstorage;
import java.awt.Color;
import javax.swing.JTextField;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JScrollBar;
import static javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED;
import static All_Forms.ItemDetails.SendObj;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADMINISTOR
 */
public class pickup_delivery extends javax.swing.JInternalFrame {
    Dstorage ds = new Dstorage();
    String clr1="";
    //global varibles...
    /**
     * Creates new form pickup_delivery
     */
    public pickup_delivery() {
        initComponents();
        ds =SendObj();
        jPanel4.setFocusable(true);
        paddPin.setText(String.valueOf(ds.pin1));
        dPin.setText(String.valueOf(ds.pin2));
        
        addInternalFrameListener(new InternalFrameAdapter() {
            public void internalFrameClosing(InternalFrameEvent e){
                JDesktopPane pane = getDesktopPane();
                int sel = JOptionPane.showConfirmDialog(null, "Do You Want to close");
                if(sel==0){ pane.removeAll();
                            pane.repaint();
                        }
                else setDefaultCloseOperation(JInternalFrame.DO_NOTHING_ON_CLOSE);
            }
            
        });
        getCityState();
    }
    
    void paintframe(String clr){
        clr1=clr;
        //JOptionPane.showMessageDialog(null, clr);
    jPanel1.setBackground(Color.decode(clr));
    jPanel2.setBackground(Color.decode(clr));
    jPanel3.setBackground(Color.decode(clr));
    jPanel4.setBackground(Color.decode(clr));
    }
    
    public void Getfocus(JTextField jtf,String s){
        if (jtf.getText().equals(s)){
        jtf.setText("");
        jtf.setForeground(Color.BLACK);}
    }
    public void LostFocus(JTextField jtf,String s){
        if (jtf.getText().equals("")){
            jtf.setText(s);
            jtf.setForeground(Color.decode("#999999"));
        }
    }
    private void getCityState(){
    pCity.setText(ds.pcity);
    pState.setText(ds.pstate);
    dCity.setText(ds.dcity);
    dState.setText(ds.dstate);
    }
         
   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        dState = new javax.swing.JTextField();
        dCity = new javax.swing.JTextField();
        dAdd2 = new javax.swing.JTextField();
        dAdd1 = new javax.swing.JTextField();
        dfName = new javax.swing.JTextField();
        dPhone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pfName = new javax.swing.JTextField();
        pPhone = new javax.swing.JTextField();
        pAdd1 = new javax.swing.JTextField();
        pAdd2 = new javax.swing.JTextField();
        pCity = new javax.swing.JTextField();
        pState = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        paddPin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dPin = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setClosable(true);
        setTitle("Pickup & Delivery");
        setToolTipText("");

        jPanel4.setBackground(new java.awt.Color(117, 148, 204));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel3.setBackground(new java.awt.Color(117, 148, 204));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Delivery Address");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel1.setBackground(new java.awt.Color(117, 148, 204));

        dState.setEditable(false);
        dState.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dState.setForeground(new java.awt.Color(153, 153, 153));
        dState.setText("Chhattisgarh");
        dState.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dStateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dStateFocusLost(evt);
            }
        });

        dCity.setEditable(false);
        dCity.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dCity.setForeground(new java.awt.Color(153, 153, 153));
        dCity.setText("City");
        dCity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dCityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dCityFocusLost(evt);
            }
        });

        dAdd2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dAdd2.setForeground(new java.awt.Color(153, 153, 153));
        dAdd2.setText("Address Line 2");
        dAdd2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dAdd2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dAdd2FocusLost(evt);
            }
        });

        dAdd1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dAdd1.setForeground(new java.awt.Color(153, 153, 153));
        dAdd1.setText("Address Line 1");
        dAdd1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dAdd1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dAdd1FocusLost(evt);
            }
        });

        dfName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dfName.setForeground(new java.awt.Color(153, 153, 153));
        dfName.setText("Full Name");
        dfName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dfNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dfNameFocusLost(evt);
            }
        });

        dPhone.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dPhone.setForeground(new java.awt.Color(153, 153, 153));
        dPhone.setText("Phone No.");
        dPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dPhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dPhoneFocusLost(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dAdd1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dfName, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(dPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dAdd2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dCity, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dState, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(dfName))
                .addGap(18, 18, 18)
                .addComponent(dAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dCity, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dState, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        jPanel2.setBackground(new java.awt.Color(117, 148, 204));

        pfName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pfName.setForeground(new java.awt.Color(153, 153, 153));
        pfName.setText("Full Name");
        pfName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pfNameFocusLost(evt);
            }
        });

        pPhone.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pPhone.setForeground(new java.awt.Color(153, 153, 153));
        pPhone.setText("Phone No.");
        pPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pPhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pPhoneFocusLost(evt);
            }
        });

        pAdd1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pAdd1.setForeground(new java.awt.Color(153, 153, 153));
        pAdd1.setText("Address Line 1");
        pAdd1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pAdd1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pAdd1FocusLost(evt);
            }
        });

        pAdd2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pAdd2.setForeground(new java.awt.Color(153, 153, 153));
        pAdd2.setText("Address Line 2");
        pAdd2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pAdd2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pAdd2FocusLost(evt);
            }
        });

        pCity.setEditable(false);
        pCity.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pCity.setForeground(new java.awt.Color(153, 153, 153));
        pCity.setText("City");
        pCity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pCityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pCityFocusLost(evt);
            }
        });

        pState.setEditable(false);
        pState.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pState.setForeground(new java.awt.Color(153, 153, 153));
        pState.setText("Chhattisgarh");
        pState.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pStateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pStateFocusLost(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pAdd1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pfName, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(pPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pAdd2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(pCity, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pState)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(pfName))
                .addGap(18, 18, 18)
                .addComponent(pAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pState, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pCity, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Pickup Address");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Pickup Address at:");

        paddPin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        paddPin.setText("---------");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Delivery Address at:");

        dPin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dPin.setText("--------");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(32, 32, 32)
                                        .addComponent(paddPin, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(45, 45, 45)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(30, 30, 30)
                                .addComponent(dPin, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dPin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paddPin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(118, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pfNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfNameFocusGained
        Getfocus(pfName,"Full Name");
         // TODO add your handling code here:
    }//GEN-LAST:event_pfNameFocusGained

    private void pfNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfNameFocusLost
        LostFocus(pfName,"Full Name");
        // TODO add your handling code here:
    }//GEN-LAST:event_pfNameFocusLost

    private void pPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pPhoneFocusGained
     Getfocus(pPhone,"Phone No.");
    }//GEN-LAST:event_pPhoneFocusGained

    private void pPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pPhoneFocusLost
        LostFocus(pPhone,"Phone No.");
    }//GEN-LAST:event_pPhoneFocusLost

    private void pAdd1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pAdd1FocusGained
        Getfocus(pAdd1,"Address Line 1");
    }//GEN-LAST:event_pAdd1FocusGained

    private void pAdd1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pAdd1FocusLost
        LostFocus(pAdd1,"Address Line 1");
    }//GEN-LAST:event_pAdd1FocusLost

    private void pAdd2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pAdd2FocusGained
        Getfocus(pAdd2,"Address Line 2");
    }//GEN-LAST:event_pAdd2FocusGained

    private void pAdd2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pAdd2FocusLost
        LostFocus(pAdd2,"Address Line 2");
    }//GEN-LAST:event_pAdd2FocusLost

    private void pCityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pCityFocusGained
        Getfocus(pCity,"City");
    }//GEN-LAST:event_pCityFocusGained

    private void pCityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pCityFocusLost
        LostFocus(pCity,"City");
    }//GEN-LAST:event_pCityFocusLost

    private void pStateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pStateFocusGained
        Getfocus(pState,"State");
    }//GEN-LAST:event_pStateFocusGained

    private void pStateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pStateFocusLost
        LostFocus(pState,"State");
    }//GEN-LAST:event_pStateFocusLost

    private void dfNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dfNameFocusGained
Getfocus(dfName,"Full Name");
    }//GEN-LAST:event_dfNameFocusGained

    private void dfNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dfNameFocusLost
LostFocus(dfName,"Full Name");        
    }//GEN-LAST:event_dfNameFocusLost

    private void dPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dPhoneFocusGained
 Getfocus(dPhone,"Phone No.");    
    }//GEN-LAST:event_dPhoneFocusGained

    private void dPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dPhoneFocusLost
LostFocus(dPhone,"Phone No.");       
    }//GEN-LAST:event_dPhoneFocusLost

    private void dAdd1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dAdd1FocusGained
 Getfocus(dAdd1,"Address Line 1");        
    }//GEN-LAST:event_dAdd1FocusGained

    private void dAdd1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dAdd1FocusLost
 LostFocus(dAdd1,"Address Line 1");        
    }//GEN-LAST:event_dAdd1FocusLost

    private void dAdd2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dAdd2FocusGained
Getfocus(dAdd2,"Address Line 2");       
    }//GEN-LAST:event_dAdd2FocusGained

    private void dAdd2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dAdd2FocusLost
LostFocus(dAdd2,"Address Line 2");       
    }//GEN-LAST:event_dAdd2FocusLost

    private void dCityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dCityFocusGained
Getfocus(dCity,"City");       
    }//GEN-LAST:event_dCityFocusGained

    private void dCityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dCityFocusLost
LostFocus(dCity,"City");     
    }//GEN-LAST:event_dCityFocusLost

    private void dStateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dStateFocusGained
Getfocus(dState,"State");
    }//GEN-LAST:event_dStateFocusGained

    private void dStateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dStateFocusLost
LostFocus(dState,"State");     
    }//GEN-LAST:event_dStateFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String addres2 = pAdd2.getText();
if (addres2.equals("Address Line 2")){
    addres2=" ";
}
        String pquery= " insert into pickup_address values("
        + "'" + ds.row           + "',"
        + "'" + pfName.getText() + "',"
        + "'" + pPhone.getText() + "',"
        + "'" + pAdd1.getText()  + addres2 + "',"
        + "'" + pCity.getText()  + "',"
        + "'" + pState.getText() + "'"
        + ");";
       

try{        
ds.pickupadd(pfName.getText(),Long.parseLong(pPhone.getText()), pAdd1.getText() + addres2, pCity.getText(), pState.getText(),pquery);
jScrollPane1.setHorizontalScrollBarPolicy(HORIZONTAL_SCROLLBAR_AS_NEEDED);
JScrollBar horizontal = jScrollPane1.getHorizontalScrollBar();
horizontal.setValue( horizontal.getMaximum() );
}
catch(Exception e){
    JOptionPane.showMessageDialog(null, "Unable to save data try again");
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String addres2 =dAdd2.getText();
if (addres2.equals("Address Line 2")){
    addres2=" ";
    
}
String dquery= " insert into delivery_address values("
        + "'" + ds.row + "',"
        + "'" + dfName.getText() + "',"
        + "'" + dPhone.getText() + "',"
        + "'" + dAdd1.getText()  + addres2 + "',"
        + "'" + dCity.getText()  + "',"
        + "'" + dState.getText() + "'"
        + ");";
        //JOptionPane.showMessageDialog(null, dquery);
        ds.getdeladd(dfName.getText(),Long.parseLong(dPhone.getText()), dAdd1.getText() + addres2, dCity.getText(), dState.getText(), dquery);
//JOptionPane.showMessageDialog(null, "sadasdsad "+dquery);
        JDesktopPane pane = getDesktopPane();
        Confirm cm = new Confirm();
        pane.add(cm);
        cm.show();
        cm.paintframe(clr1);
        try {
            cm.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(pickup_delivery.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dAdd1;
    private javax.swing.JTextField dAdd2;
    private javax.swing.JTextField dCity;
    private javax.swing.JTextField dPhone;
    private javax.swing.JLabel dPin;
    private javax.swing.JTextField dState;
    private javax.swing.JTextField dfName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField pAdd1;
    private javax.swing.JTextField pAdd2;
    private javax.swing.JTextField pCity;
    private javax.swing.JTextField pPhone;
    private javax.swing.JTextField pState;
    private javax.swing.JLabel paddPin;
    private javax.swing.JTextField pfName;
    // End of variables declaration//GEN-END:variables
}
